name: Build and Deploy to S3

on:
  workflow_dispatch:
  schedule:
    - cron: '55 * * * *'
  push:
    branches:
      - production

      
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20.3.1' 
        ref: production

    - name: Set environment variables
      run: echo "GATSBY_S3_BUCKET=${{ secrets.GATSBY_S3_BUCKET }}" >> $GITHUB_ENV


    - name: Install Dependencies
      run: npm install

    - name: Application build
      run: npm run build
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}



    - name: Install gatsby-plugin-s3
      run: npm install -g gatsby-plugin-s3
    - name: Deploy to S3
      run: |
        yes | gatsby-plugin-s3 deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GATSBY_S3_BUCKET: ${{ secrets.GATSBY_S3_BUCKET }}




        
